# Stage 1: Build
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Run
FROM nginx:alpine

# Copie de la configuration nginx personnalisée si nécessaire
# COPY nginx.conf /etc/nginx/nginx.conf

# Copie des fichiers de build
COPY --from=build /app/dist/front-bot/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 